sudo: false
language: node_js
before_install:
  - npm i -g makeshift && makeshift -r https://registry.npmjs.org
node_js:
  - '8'
deploy:
  provider: npm
  email: "klauswk1@gmail.com"
  api_key: $NPM_TOKEN
  on: 
    branch: master
    skip_cleanup: true
